name: 'Install Lokalise CLI'
description: 'Action to install Lokalise CLI v2'
inputs:
  force-install:
    description: 'Force installation if Lokalise CLI is already installed'
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - name: Install Lokalise CLI
      shell: bash
      id: install-lokalise
      env:
        FORCE_INSTALL: ${{ inputs.force-install }}
      run: |
        set -e
        chmod +x "${{ github.action_path }}/src/install-lokalise.sh"
        "${{ github.action_path }}/src/install-lokalise.sh"