name: 'Install Lokalise CLI'
description: 'Action to install Lokalise CLI v2'
inputs:
  force-install:
    description: 'Force installation if Lokalise CLI is already installed'
    required: false
    default: 'false'

  target-version:
    description: 'Version of Lokalise CLI to install (e.g., 3.1.1)'
    required: false
    default: ''

branding:
  icon: 'box'
  color: 'black'

permissions:
  contents: read
  
runs:
  using: 'composite'
  steps:
    - name: Install Lokalise CLI
      shell: bash
      id: install-lokalise
      env:
        FORCE_INSTALL: ${{ inputs.force-install }}
        LOKALISE_CLI_VERSION: ${{ inputs.target-version }}
      run: |
        set -euo pipefail

        SCRIPT="${{ github.action_path }}/src/install-lokalise.sh"
        if [[ ! -f "$SCRIPT" ]]; then
          echo "Helper script not found: $SCRIPT"
          exit 1
        fi

        chmod +x "$SCRIPT"
        "$SCRIPT"